name: GoodOpenBoxDriver
options:
  bundleIdPrefix: com.goodopenbox
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.4"

packages:
  GOBShared:
    path: ../Packages/GOBShared

targets:
  GoodOpenBoxDriver:
    type: application
    platform: iOS
    sources:
      - path: Sources
    resources:
      - path: Assets.xcassets
    dependencies:
      - package: GOBShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.goodopenbox.driver
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "GOB Driver"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "We need your location to navigate to delivery addresses."
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
