name: GoodOpenBoxApp
options:
  bundleIdPrefix: com.goodopenbox
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.4"

packages:
  GOBShared:
    path: ../Packages/GOBShared

targets:
  GoodOpenBoxApp:
    type: application
    platform: iOS
    sources:
      - path: Sources
    resources:
      - path: Assets.xcassets
    dependencies:
      - package: GOBShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.goodopenbox.marketplace
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Good Open Box"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
